#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: d8a7ad5e21abac17cf5dbc471f92fecfb4d535b7
  - name: quay.io/nexodus/envsubst
    newTag: d8a7ad5e21abac17cf5dbc471f92fecfb4d535b7
  - name: quay.io/nexodus/frontend
    newTag: d8a7ad5e21abac17cf5dbc471f92fecfb4d535b7
  - name: quay.io/nexodus/go-ipam
    newTag: d8a7ad5e21abac17cf5dbc471f92fecfb4d535b7
